import { Component } from '@angular/core';
import { MovieCardComponent } from '../movie-card/movie-card.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-recommendation',
  standalone: true,
  imports: [MovieCardComponent, CommonModule],
  templateUrl: './recommendation.component.html',
  styleUrl: './recommendation.component.scss',
})
export class RecommendationComponent {
  movies = [
    {
      id: '8be9f37a-1162-4d98-9b41-f7ccd45f093a',
      movie_id: 8831,
      original_title: 'Timecop',
      original_language: 'en',
      overview:
        'An officer for a security agency that regulates time travel, must fend for his life against a shady politician who has a tie to his past.',
      popularity: 14.34,
      poster_path:
        'https://image.tmdb.org/t/p/original/qDjne2UffjOpZAg9cFmzteWqhd3.jpg',
      backdrop_path:
        'https://image.tmdb.org/t/p/original/7A4FJCsG26vOi9TUwFXdZMuzmOh.jpg',
      release_date: 'Thu, 09/15/1994',
      vote_average: 6,
      vote_count: 1053,
      adult: 0,
      created_at: null,
      updated_at: null,
      casts: [
        {
          id: '5c109823-a917-4fc4-b73e-648f1e467fe1',
          movie_id: 8831,
          name: 'Ron Silver',
          original_name: 'Ron Silver',
          popularity: '6.95',
          profile_path:
            'https://image.tmdb.org/t/p/original/6urQBScK7Vq6q5niaMMEmzW3DGP.jpg',
          character: 'Senator Aaron McComb',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'ceb11dc1-35d9-4943-8dbd-fa58c5a3a1e9',
          movie_id: 8831,
          name: 'Kenneth Welsh',
          original_name: 'Kenneth Welsh',
          popularity: '6.014',
          profile_path:
            'https://image.tmdb.org/t/p/original/hsmY2HaIdOEoTBtwFPxQLyLymYw.jpg',
          character: 'Utley',
          created_at: null,
          updated_at: null,
        },
        {
          id: '94998038-a72a-45ea-b81a-670555e4c618',
          movie_id: 8831,
          name: 'James Lew',
          original_name: 'James Lew',
          popularity: '5.72',
          profile_path:
            'https://image.tmdb.org/t/p/original/wuC0B13IutImC1AJ7VUxBCuZJVg.jpg',
          character: 'Knife #1',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e83375b0-413e-4f99-b512-26cb38fba319',
          movie_id: 8831,
          name: 'Veena Sood',
          original_name: 'Veena Sood',
          popularity: '4.976',
          profile_path:
            'https://image.tmdb.org/t/p/original/yze2fvd4rvzovqyjtKbCpFaw1UM.jpg',
          character: 'Nurse',
          created_at: null,
          updated_at: null,
        },
        {
          id: '617fc7b9-1217-4d03-9b5e-607479f1e259',
          movie_id: 8831,
          name: 'Gabrielle Rose',
          original_name: 'Gabrielle Rose',
          popularity: '4.751',
          profile_path:
            'https://image.tmdb.org/t/p/original/obWfgaR4YBk648USvpLrJC64DVU.jpg',
          character: 'Judge Marshall',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'fb2fc1f4-3d19-48ed-914b-7d0b8c48f939',
          movie_id: 8831,
          name: 'Jason Schombing',
          original_name: 'Jason Schombing',
          popularity: '4.59',
          profile_path:
            'https://image.tmdb.org/t/p/original/tQCjZVPPQJmVAdgPQacllN00bfW.jpg',
          character: 'Atwood',
          created_at: null,
          updated_at: null,
        },
        {
          id: '8e2262d4-34ca-446a-8fd6-ceb55a420bac',
          movie_id: 8831,
          name: 'Gloria Reuben',
          original_name: 'Gloria Reuben',
          popularity: '4.536',
          profile_path:
            'https://image.tmdb.org/t/p/original/7Ttd3nj1M9P8YE9LzCvGZcvPUQR.jpg',
          character: 'Fielding',
          created_at: null,
          updated_at: null,
        },
        {
          id: '25d7f478-b673-43ef-91fb-15088b98e3a2',
          movie_id: 8831,
          name: 'Steven Lambert',
          original_name: 'Steven Lambert',
          popularity: '4.403',
          profile_path:
            'https://image.tmdb.org/t/p/original/4xXQXJHECq50ea7C8VeBY0uN3ms.jpg',
          character: 'Lansing',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'dfb0a683-fbfc-4000-96eb-74554a0a2d0e',
          movie_id: 8831,
          name: 'Kim Kondrashoff',
          original_name: 'Kim Kondrashoff',
          popularity: '4.266',
          profile_path:
            'https://image.tmdb.org/t/p/original/uL4rVpEtniiJw0LUuWqKLrGkQWw.jpg',
          character: 'Security Agent #1',
          created_at: null,
          updated_at: null,
        },
        {
          id: '42d8d0b6-561b-4897-9098-754cc87917fa',
          movie_id: 8831,
          name: 'Brad Loree',
          original_name: 'Brad Loree',
          popularity: '4.121',
          profile_path:
            'https://image.tmdb.org/t/p/original/jn2QDZPKz49gk8LtBXF1S8EnQd1.jpg',
          character: 'Reyes',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'f161a8b7-edf2-4ef6-ab86-513541d234ef',
          movie_id: 8831,
          name: 'Charles Andre',
          original_name: 'Charles Andre',
          popularity: '4.022',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Knife #2',
          created_at: null,
          updated_at: null,
        },
        {
          id: '3f14d688-aace-4063-9e45-3745687865b7',
          movie_id: 8831,
          name: 'Jean-Claude Van Damme',
          original_name: 'Jean-Claude Van Damme',
          popularity: '33.66',
          profile_path:
            'https://image.tmdb.org/t/p/original/7DP3bm3MS0qa0L8tBLHGebbCu6H.jpg',
          character: 'Max Walker',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'b3bcc30e-79e3-465d-82d6-f56c5c01eb97',
          movie_id: 8831,
          name: 'Malcolm Stewart',
          original_name: 'Malcolm Stewart',
          popularity: '3.949',
          profile_path:
            'https://image.tmdb.org/t/p/original/8BsKvYKYkjvNxsBqs0ZRKhwdpXE.jpg',
          character: 'Nelson',
          created_at: null,
          updated_at: null,
        },
        {
          id: '91b24a5a-cde8-4dea-9b30-1e476f26d66d',
          movie_id: 8831,
          name: 'Kevin McNulty',
          original_name: 'Kevin McNulty',
          popularity: '3.724',
          profile_path:
            'https://image.tmdb.org/t/p/original/jaXuLA5zYPVzfG8wLtnD2O4aveA.jpg',
          character: 'Parker',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'bf890a1b-a0d2-48b9-9af6-d480708c163e',
          movie_id: 8831,
          name: 'Callum Keith Rennie',
          original_name: 'Callum Keith Rennie',
          popularity: '3.672',
          profile_path:
            'https://image.tmdb.org/t/p/original/zOeA4IR4xYde2VlDsHZy2SoPZkc.jpg',
          character: 'Stranger',
          created_at: null,
          updated_at: null,
        },
        {
          id: '155762bb-eb6a-4ed3-8818-e3a931b0d176',
          movie_id: 8831,
          name: 'Tom McBeath',
          original_name: 'Tom McBeath',
          popularity: '3.471',
          profile_path:
            'https://image.tmdb.org/t/p/original/vKeYC2KlMiq4S48ZafMll7jl9CJ.jpg',
          character: 'T.E.C. Technician',
          created_at: null,
          updated_at: null,
        },
        {
          id: '5aeec813-4e5c-4783-83c5-5ad7362c2e0b',
          movie_id: 8831,
          name: 'J.J. Makaro',
          original_name: 'J.J. Makaro',
          popularity: '3.466',
          profile_path:
            'https://image.tmdb.org/t/p/original/y1Ec2iASfEU4Mr3I05xXHl0PmDQ.jpg',
          character: 'McComb Guard #1',
          created_at: null,
          updated_at: null,
        },
        {
          id: '662f1f2d-e577-42d7-b83f-8e8c9d7203bb',
          movie_id: 8831,
          name: 'Duncan Fraser',
          original_name: 'Duncan Fraser',
          popularity: '3.447',
          profile_path:
            'https://image.tmdb.org/t/p/original/ckiY9K7fwH5KRuTE3IM5kelwm0c.jpg',
          character: 'Irish Cop',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e2ee12c1-7e2a-415e-9050-7b9282d6f83b',
          movie_id: 8831,
          name: 'Scott Nicholson',
          original_name: 'Scott Nicholson',
          popularity: '3.35',
          profile_path:
            'https://image.tmdb.org/t/p/original/61MxcJoexBrV3naICrJYeLV2HCV.jpg',
          character: 'Guard #1',
          created_at: null,
          updated_at: null,
        },
        {
          id: '6da4d691-264c-4c90-944d-516f7d17a66b',
          movie_id: 8831,
          name: 'Mike Mitchell',
          original_name: 'Mike Mitchell',
          popularity: '3.311',
          profile_path:
            'https://image.tmdb.org/t/p/original/hiDSQRsnfbSgWQQO0kMf4onr4qD.jpg',
          character: 'McComb Man #2',
          created_at: null,
          updated_at: null,
        },
        {
          id: '772b88d0-ddfa-46ac-8212-653f2604de9d',
          movie_id: 8831,
          name: 'Richard Faraci',
          original_name: 'Richard Faraci',
          popularity: '3.283',
          profile_path:
            'https://image.tmdb.org/t/p/original/kb9mJ8gPJD6iPshwPg9ZchBHK95.jpg',
          character: 'Cole',
          created_at: null,
          updated_at: null,
        },
        {
          id: '05ddc4f8-47a3-44b0-b36d-37a979491f51',
          movie_id: 8831,
          name: 'Bruce McGill',
          original_name: 'Bruce McGill',
          popularity: '25.296',
          profile_path:
            'https://image.tmdb.org/t/p/original/9zF43TgWiO3AlKC4I48S7ZK09lK.jpg',
          character: 'Commander Eugene Matuzak',
          created_at: null,
          updated_at: null,
        },
        {
          id: '452e81c1-95aa-4cfc-be0b-b3c9ba7dbd10',
          movie_id: 8831,
          name: 'Ernie Jackson',
          original_name: 'Ernie Jackson',
          popularity: '2.887',
          profile_path:
            'https://image.tmdb.org/t/p/original/85PqJrrUs6BQYJYqF7qlvgFARNz.jpg',
          character: 'Guard #2',
          created_at: null,
          updated_at: null,
        },
        {
          id: '25d683c9-3c97-4062-a188-ad9ef6d7460c',
          movie_id: 8831,
          name: 'Brent Woolsey',
          original_name: 'Brent Woolsey',
          popularity: '2.358',
          profile_path:
            'https://image.tmdb.org/t/p/original/jv3MCoUVGomAgO4TbXXuamZTaOX.jpg',
          character: 'Shotgun',
          created_at: null,
          updated_at: null,
        },
        {
          id: '153010ce-3f09-48e4-8d39-d3db34338b89',
          movie_id: 8831,
          name: 'Scott Lawrence',
          original_name: 'Scott Lawrence',
          popularity: '2.335',
          profile_path:
            'https://image.tmdb.org/t/p/original/8lwnmlHN6QPK75NwfufsIFZZhmB.jpg',
          character: 'Spota',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e03ea061-3db7-42f9-a7a4-7608fe42a517',
          movie_id: 8831,
          name: 'Mia Sara',
          original_name: 'Mia Sara',
          popularity: '16.325',
          profile_path:
            'https://image.tmdb.org/t/p/original/ciFYqIYLdaRluqbljpYdeYvnFIw.jpg',
          character: 'Melissa Walker',
          created_at: null,
          updated_at: null,
        },
        {
          id: '803c27f4-0718-4a81-9638-2bef3bd4780f',
          movie_id: 8831,
          name: 'Ian Tracey',
          original_name: 'Ian Tracey',
          popularity: '11.335',
          profile_path:
            'https://image.tmdb.org/t/p/original/dUzzLVVUF0pvGzS3xrIZ5tiC2TT.jpg',
          character: 'Soldier',
          created_at: null,
          updated_at: null,
        },
        {
          id: '887069db-a474-4ac0-a3a8-8f925e0aca39',
          movie_id: 8831,
          name: 'Frank Cassini',
          original_name: 'Frank Cassini',
          popularity: '1.931',
          profile_path:
            'https://image.tmdb.org/t/p/original/uGBF867qyUWNjhewE6RZ8rbnUB4.jpg',
          character: 'T.E.C. Agent',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'aaf7c4ce-3264-49a5-bb51-6d48d641d283',
          movie_id: 8831,
          name: 'Laura Murdoch',
          original_name: 'Laura Murdoch',
          popularity: '1.931',
          profile_path:
            'https://image.tmdb.org/t/p/original/eo2kazEfT5MvlwM6DlnIzUNZSOj.jpg',
          character: 'Virtual Reality Woman',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'be7a22f7-969d-4d49-9deb-48b52e8431e4',
          movie_id: 8831,
          name: 'Kelli Fox',
          original_name: 'Kelli Fox',
          popularity: '1.859',
          profile_path:
            'https://image.tmdb.org/t/p/original/rWbfvKrINW9EZHF7sCif7ZxiKIk.jpg',
          character: 'Aide',
          created_at: null,
          updated_at: null,
        },
        {
          id: '5e9fc26f-67a7-4488-bd8c-3bd9f220415f',
          movie_id: 8831,
          name: 'Tony Morelli',
          original_name: 'Tony Morelli',
          popularity: '1.857',
          profile_path:
            'https://image.tmdb.org/t/p/original/jeh4YbLQgFg8Au5albydEPeNNG1.jpg',
          character: 'Tweed',
          created_at: null,
          updated_at: null,
        },
        {
          id: '9ba257a1-68b4-4f66-b682-60cd3fd5c5ab',
          movie_id: 8831,
          name: 'Alfonso Quijada',
          original_name: 'Alfonso Quijada',
          popularity: '1.571',
          profile_path:
            'https://image.tmdb.org/t/p/original/d9jUAssHaBOtwHGOeuCrVN1lOPm.jpg',
          character: 'Photographer',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'ed6ce9c8-5192-4f15-8915-2e631a2f9889',
          movie_id: 8831,
          name: 'Scott Bellis',
          original_name: 'Scott Bellis',
          popularity: '1.554',
          profile_path:
            'https://image.tmdb.org/t/p/original/3YgfumtSHiqWfy3EEX3mLvOaEIR.jpg',
          character: 'Ricky',
          created_at: null,
          updated_at: null,
        },
        {
          id: '9a8e0479-86ca-4f43-81a3-dc70fca49984',
          movie_id: 8831,
          name: 'Glen Roald',
          original_name: 'Glen Roald',
          popularity: '1.38',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Doorman',
          created_at: null,
          updated_at: null,
        },
        {
          id: '42facb66-f304-435e-b652-1a10c924897a',
          movie_id: 8831,
          name: 'David Jacox',
          original_name: 'David Jacox',
          popularity: '1.31',
          profile_path:
            'https://image.tmdb.org/t/p/original/c3cKOEB1jgFJkiDblugf1zuxwbg.jpg',
          character: 'McComb Man #1',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'a5d46244-87d1-4cac-97c2-c93f57b4e5ec',
          movie_id: 8831,
          name: 'Yves Cameron',
          original_name: 'Yves Cameron',
          popularity: '1.294',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'McComb Guard #2',
          created_at: null,
          updated_at: null,
        },
        {
          id: '600c166b-1576-462f-9223-b7849c947430',
          movie_id: 8831,
          name: 'Tom Glass',
          original_name: 'Tom Glass',
          popularity: '1.286',
          profile_path:
            'https://image.tmdb.org/t/p/original/1ZaVjYRCvgDx5AqjfCbuQxjvTvF.jpg',
          character: 'Wagon Driver',
          created_at: null,
          updated_at: null,
        },
        {
          id: '65cbb8b2-b2a1-474e-a60d-a4d348c40474',
          movie_id: 8831,
          name: "Sean O'Byrne",
          original_name: "Sean O'Byrne",
          popularity: '1.248',
          profile_path:
            'https://image.tmdb.org/t/p/original/cedCqk5mxnOGQf4JvLofgUhBsTF.jpg',
          character: 'Aide Lawrence',
          created_at: null,
          updated_at: null,
        },
        {
          id: '467f3f58-1009-4fe7-994c-fcca2b1d94c5',
          movie_id: 8831,
          name: 'Jacob Rupp',
          original_name: 'Jacob Rupp',
          popularity: '1.22',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Palmer',
          created_at: null,
          updated_at: null,
        },
        {
          id: '476088e9-ed31-4358-b906-5bb2d0222049',
          movie_id: 8831,
          name: 'Tom Eirikson',
          original_name: 'Tom Eirikson',
          popularity: '1.178',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Guard #3',
          created_at: null,
          updated_at: null,
        },
        {
          id: '2bdb6742-e86f-4849-ae08-42a3265df74b',
          movie_id: 8831,
          name: 'Lon Katzman',
          original_name: 'Lon Katzman',
          popularity: '1.105',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Handlebar',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e6740dfa-3da9-4a3a-88b0-77642741e68b',
          movie_id: 8831,
          name: 'Shane Kelly',
          original_name: 'Shane Kelly',
          popularity: '1.046',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Rollerblades',
          created_at: null,
          updated_at: null,
        },
        {
          id: '167db2d9-19f7-4143-833c-7dfdb6e62def',
          movie_id: 8831,
          name: 'Nick Hyams',
          original_name: 'Nick Hyams',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Newsboy',
          created_at: null,
          updated_at: null,
        },
        {
          id: '549d460c-8674-4982-b16d-56b6adbdc1de',
          movie_id: 8831,
          name: 'Theodore Thomas',
          original_name: 'Theodore Thomas',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Pete',
          created_at: null,
          updated_at: null,
        },
        {
          id: '6435ab63-8126-4aa9-a5a0-9fca045876a7',
          movie_id: 8831,
          name: 'Doris Blomgren',
          original_name: 'Doris Blomgren',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Old Woman',
          created_at: null,
          updated_at: null,
        },
        {
          id: '675a34b1-78aa-4b0c-b113-d3d29d87d0ae',
          movie_id: 8831,
          name: 'Pamela Martin',
          original_name: 'Pamela Martin',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'TV Commentator',
          created_at: null,
          updated_at: null,
        },
        {
          id: '6979782f-fea0-4429-838c-12f25c1c7dd3',
          movie_id: 8831,
          name: 'Dalton Fisher',
          original_name: 'Dalton Fisher',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Washington Cop',
          created_at: null,
          updated_at: null,
        },
        {
          id: '6cd5e43f-87e9-49b3-a751-bab337311433',
          movie_id: 8831,
          name: 'Yvette Ferguson',
          original_name: 'Yvette Ferguson',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Atwood Secretary',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'bd0891d2-6a33-49c4-aa1c-377a53816ca0',
          movie_id: 8831,
          name: 'Cole Bradsen',
          original_name: 'Cole Bradsen',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Boy',
          created_at: null,
          updated_at: null,
        },
      ],
    },
    {
      id: '373132f0-d3e2-4cd7-ba17-96f35fcdbb3e',
      movie_id: 15997,
      original_title: 'The Land Before Time II: The Great Valley Adventure',
      original_language: 'en',
      overview:
        'This time, while building a hideaway in their new home of the Great Valley, Littlefoot and the gang rescue a mysterious egg from two scheming egg-nappers and make a starling surprise - and new friend - when the egg hatches.',
      popularity: 19.82,
      poster_path:
        'https://image.tmdb.org/t/p/original/1lIkU6gbqMx4oRDGegawLdQdLJD.jpg',
      backdrop_path:
        'https://image.tmdb.org/t/p/original/8Db2ogq0e4UepMMxwqdv79YJMNq.jpg',
      release_date: 'Mon, 12/12/1994',
      vote_average: 6.3,
      vote_count: 515,
      adult: 0,
      created_at: null,
      updated_at: null,
      casts: [
        {
          id: '0d36e943-6055-414b-baa5-eb3cbd1f5c3a',
          movie_id: 15997,
          name: 'Jeff Bennett',
          original_name: 'Jeff Bennett',
          popularity: '9.795',
          profile_path:
            'https://image.tmdb.org/t/p/original/p78svoOr99IA2oBOUzAH9cnPOwf.jpg',
          character: 'Petrie / Ozzy (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '657aa229-b2c7-4a45-bc1a-b1700d719641',
          movie_id: 15997,
          name: 'Rob Paulsen',
          original_name: 'Rob Paulsen',
          popularity: '8.827',
          profile_path:
            'https://image.tmdb.org/t/p/original/7buvKWIjPlspqruaO3b28V5owJr.jpg',
          character: 'Spike / Strut / Chomper (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e6e6004a-bbd3-4bae-8f6b-5cd857d70b38',
          movie_id: 15997,
          name: 'Kenneth Mars',
          original_name: 'Kenneth Mars',
          popularity: '5.499',
          profile_path:
            'https://image.tmdb.org/t/p/original/5ueZGenOr87KfMENzffdtGn3AQ9.jpg',
          character: 'Grandpa (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'ca384471-b577-44d4-9f9f-ab20cbf82f5a',
          movie_id: 15997,
          name: 'Linda Gary',
          original_name: 'Linda Gary',
          popularity: '4.363',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Grandma (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'b604bc70-4a2d-48f3-9bc4-4e3bd096e9c4',
          movie_id: 15997,
          name: 'Candace Hutson',
          original_name: 'Candace Hutson',
          popularity: '3.23',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Cera (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '3c88fcb3-744e-48bb-8125-be3190c134c9',
          movie_id: 15997,
          name: 'John Ingle',
          original_name: 'John Ingle',
          popularity: '3.186',
          profile_path:
            'https://image.tmdb.org/t/p/original/cFrwER1BE3WnXwfXdlxAI03meCo.jpg',
          character: "Narrator / Cera's Father (voice)",
          created_at: null,
          updated_at: null,
        },
        {
          id: 'cab00af1-55b7-42e4-b251-ddecd7af9974',
          movie_id: 15997,
          name: 'Tress MacNeille',
          original_name: 'Tress MacNeille',
          popularity: '14.671',
          profile_path:
            'https://image.tmdb.org/t/p/original/gI2LsgByvSffQY34vabVnPmrHzw.jpg',
          character: "Ducky's Mom / Petrie's Mom / Mother Maiasaurus (voice)",
          created_at: null,
          updated_at: null,
        },
        {
          id: 'a496dccb-7bbe-4124-8d24-e82434dad957',
          movie_id: 15997,
          name: 'Scott McAfee',
          original_name: 'Scott McAfee',
          popularity: '1.72',
          profile_path:
            'https://image.tmdb.org/t/p/original/meKYkzavWpSg2KheDlMlUmZC4za.jpg',
          character: 'Littlefoot (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '16e3bf17-ca3b-4ad9-817c-6752eaf25243',
          movie_id: 15997,
          name: 'Heather Hogan',
          original_name: 'Heather Hogan',
          popularity: '1.541',
          profile_path:
            'https://image.tmdb.org/t/p/original/fKgZ9EGgr7mUFJ76LS6dIeTR1PB.jpg',
          character: 'Ducky (voice)',
          created_at: null,
          updated_at: null,
        },
      ],
    },
    {
      id: '9d4bfda6-06bf-4ba1-a700-e773fa878c72',
      movie_id: 9552,
      original_title: 'The Exorcist',
      original_language: 'en',
      overview:
        '12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.',
      popularity: 152.45,
      poster_path:
        'https://image.tmdb.org/t/p/original/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg',
      backdrop_path:
        'https://image.tmdb.org/t/p/original/xcjJ5khg2yzOa282mza39Lbrm7j.jpg',
      release_date: 'Wed, 12/26/1973',
      vote_average: 7.7,
      vote_count: 7308,
      adult: 0,
      created_at: null,
      updated_at: null,
      casts: [
        {
          id: 'cec99e82-b97e-4455-8be0-304fc91209f9',
          movie_id: 9552,
          name: 'Jason Miller',
          original_name: 'Jason Miller',
          popularity: '8.315',
          profile_path:
            'https://image.tmdb.org/t/p/original/4dwatFQJnBvS51SjsqnG4ZC4ItZ.jpg',
          character: 'Father Damien Karras',
          created_at: null,
          updated_at: null,
        },
        {
          id: '89e90851-ea37-4ab2-8114-3df70ef253ad',
          movie_id: 9552,
          name: 'Eileen Dietz',
          original_name: 'Eileen Dietz',
          popularity: '7.332',
          profile_path:
            'https://image.tmdb.org/t/p/original/o2G8NDUVVMkE6azdOoKtCrFHmO8.jpg',
          character: 'Demon / Regan Double (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '887655e4-7a2e-46da-9da0-f0d87c685eaf',
          movie_id: 9552,
          name: 'Kitty Winn',
          original_name: 'Kitty Winn',
          popularity: '6.38',
          profile_path:
            'https://image.tmdb.org/t/p/original/9qO3EfnwYkiuol2z8jzetCIR92f.jpg',
          character: 'Sharon Spencer',
          created_at: null,
          updated_at: null,
        },
        {
          id: '16b04cc9-d0e2-4f1a-aad4-37e1dd805df6',
          movie_id: 9552,
          name: 'Mercedes McCambridge',
          original_name: 'Mercedes McCambridge',
          popularity: '6.242',
          profile_path:
            'https://image.tmdb.org/t/p/original/vgJsNh4g6PMBekuJfEoazWySqWs.jpg',
          character: 'Demon (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '53224046-f9f2-427b-a22c-c0eda669a790',
          movie_id: 9552,
          name: 'Donna Mitchell',
          original_name: 'Donna Mitchell',
          popularity: '5.422',
          profile_path:
            'https://image.tmdb.org/t/p/original/xl8nnJBzNj0cqTAB3nk7GkKqmRV.jpg',
          character: 'Mary Jo Perrin',
          created_at: null,
          updated_at: null,
        },
        {
          id: '112bd9e9-987a-41ff-b59a-4070e8b6ff91',
          movie_id: 9552,
          name: 'Jack MacGowran',
          original_name: 'Jack MacGowran',
          popularity: '5.269',
          profile_path:
            'https://image.tmdb.org/t/p/original/rpQ8woHjo3ZzsJNT3RJSfJGDNIQ.jpg',
          character: 'Burke Dennings',
          created_at: null,
          updated_at: null,
        },
        {
          id: '43e70e99-e22a-4f49-8ac8-8a1f3da9e816',
          movie_id: 9552,
          name: 'William Peter Blatty',
          original_name: 'William Peter Blatty',
          popularity: '4.509',
          profile_path:
            'https://image.tmdb.org/t/p/original/5AWZXT3hBhM6M5NbiGmC3cPFAVC.jpg',
          character: 'The Producer (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '095f8aa1-291a-49ed-858f-8aae4db580bb',
          movie_id: 9552,
          name: "William O'Malley",
          original_name: "William O'Malley",
          popularity: '3.669',
          profile_path:
            'https://image.tmdb.org/t/p/original/AlDM1ZmkY7KfcnRFSQ8hLStlruD.jpg',
          character: 'Father Joseph Kevin Dyer',
          created_at: null,
          updated_at: null,
        },
        {
          id: '09323599-fd7f-42c5-bf1d-9785e2e94b53',
          movie_id: 9552,
          name: 'Rudolf Sch\u00fcndler',
          original_name: 'Rudolf Sch\u00fcndler',
          popularity: '3.643',
          profile_path:
            'https://image.tmdb.org/t/p/original/cGQbR4f9cLRld2j8CWPXP2c2g4k.jpg',
          character: 'Karl',
          created_at: null,
          updated_at: null,
        },
        {
          id: '8b218d1d-b25a-40a8-9288-e391311e2d00',
          movie_id: 9552,
          name: 'Barton Heyman',
          original_name: 'Barton Heyman',
          popularity: '3.581',
          profile_path:
            'https://image.tmdb.org/t/p/original/6oyn9WMxi8GjzHAFm3weJBUejkI.jpg',
          character: 'Dr. Klein',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'fcd1ff3d-8d1b-4df8-80b0-4d980d1891ac',
          movie_id: 9552,
          name: 'Titos Vandis',
          original_name: 'Titos Vandis',
          popularity: '3.255',
          profile_path:
            'https://image.tmdb.org/t/p/original/p3rT1vXOMWNYfV7HJOp0tMhzu6E.jpg',
          character: 'Uncle John',
          created_at: null,
          updated_at: null,
        },
        {
          id: '7970a4e2-895c-4a87-9cb4-c328195e8840',
          movie_id: 9552,
          name: 'Arthur Storch',
          original_name: 'Arthur Storch',
          popularity: '3.131',
          profile_path:
            'https://image.tmdb.org/t/p/original/7SBFggnUovIUvt89xZ9D5XskoQJ.jpg',
          character: 'Psychiatrist',
          created_at: null,
          updated_at: null,
        },
        {
          id: '832c4da7-05b6-480a-9aad-89fcc22f5b76',
          movie_id: 9552,
          name: 'Linda Blair',
          original_name: 'Linda Blair',
          popularity: '29.274',
          profile_path:
            'https://image.tmdb.org/t/p/original/3jswDdLDsmSAO4ZtVPwyKAp6D5d.jpg',
          character: 'Regan MacNeil',
          created_at: null,
          updated_at: null,
        },
        {
          id: '60bc5e36-df86-4b36-b1c4-8dd8b932f571',
          movie_id: 9552,
          name: 'Ellen Burstyn',
          original_name: 'Ellen Burstyn',
          popularity: '26.865',
          profile_path:
            'https://image.tmdb.org/t/p/original/rDClU5Mvj6SrDxAdZMGPDgGUBiw.jpg',
          character: 'Chris MacNeil',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'c82eefa5-017c-41b0-826e-6d115e7afca7',
          movie_id: 9552,
          name: 'Mary Boylan',
          original_name: 'Mary Boylan',
          popularity: '2.967',
          profile_path:
            'https://image.tmdb.org/t/p/original/yxPBoTfF0AircwcF3K1dlVTYKYK.jpg',
          character: 'First Mental Patient (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'f6d36c33-a82d-492b-8d6a-7283c7a1184e',
          movie_id: 9552,
          name: 'Robert Symonds',
          original_name: 'Robert Symonds',
          popularity: '2.53',
          profile_path:
            'https://image.tmdb.org/t/p/original/q5hinYiY8BpzK6PlIG105thL3us.jpg',
          character: 'Dr. Taney',
          created_at: null,
          updated_at: null,
        },
        {
          id: '6fc761de-118e-442d-be67-53dbd30191a3',
          movie_id: 9552,
          name: 'John Mahon',
          original_name: 'John Mahon',
          popularity: '2.203',
          profile_path:
            'https://image.tmdb.org/t/p/original/HQ5v471RZCcWhl9qY4cImUf5tP.jpg',
          character: 'Language Lab Director',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'ab56f178-bc37-412f-9e73-d0ee7dab935b',
          movie_id: 9552,
          name: 'Max von Sydow',
          original_name: 'Max von Sydow',
          popularity: '16.763',
          profile_path:
            'https://image.tmdb.org/t/p/original/fOzSDFqMx84NR7PSv36P7j0Qf1q.jpg',
          character: 'Father Lankester Merrin',
          created_at: null,
          updated_at: null,
        },
        {
          id: '915ef88f-e960-4844-be58-108ff6d2b383',
          movie_id: 9552,
          name: 'Lee J. Cobb',
          original_name: 'Lee J. Cobb',
          popularity: '10.817',
          profile_path:
            'https://image.tmdb.org/t/p/original/aSQj0q6l734wxzutUGuYCGtJmZv.jpg',
          character: 'Lt. Bill Kinderman',
          created_at: null,
          updated_at: null,
        },
        {
          id: '84e570e6-1c79-4204-ba43-262fbbc08bb2',
          movie_id: 9552,
          name: 'Wallace Rooney',
          original_name: 'Wallace Rooney',
          popularity: '1.737',
          profile_path:
            'https://image.tmdb.org/t/p/original/xcFGbEz1HTRXTU6cz6ftpxF7mPZ.jpg',
          character: 'Bishop Michael',
          created_at: null,
          updated_at: null,
        },
        {
          id: '1d4300b3-3bae-446f-809d-fd6f73754890',
          movie_id: 9552,
          name: 'Vasiliki Maliaros',
          original_name: 'Vasiliki Maliaros',
          popularity: '1.4',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Mary Karras',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'a041ea77-4511-4d80-9ce1-580845d211a3',
          movie_id: 9552,
          name: 'Rita Sakellariou',
          original_name: 'Rita Sakellariou',
          popularity: '1.4',
          profile_path:
            'https://image.tmdb.org/t/p/original/tjeLpNjFxjLtxjpKwx15ErF9YWu.jpg',
          character: '(her voice on the radio)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'c637f97c-9752-4181-8742-08bb0251aa01',
          movie_id: 9552,
          name: 'Ron Faber',
          original_name: 'Ron Faber',
          popularity: '1.388',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Chuck / Demon (voice)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'f6937866-107b-43b5-adbe-f93582f647c0',
          movie_id: 9552,
          name: 'Joanne Dusseau',
          original_name: 'Joanne Dusseau',
          popularity: '1.385',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: "Senator's Wife (uncredited)",
          created_at: null,
          updated_at: null,
        },
        {
          id: '9f0c2a7f-1413-41de-bc38-c6938af67855',
          movie_id: 9552,
          name: 'Roy Cooper',
          original_name: 'Roy Cooper',
          popularity: '1.379',
          profile_path:
            'https://image.tmdb.org/t/p/original/vucD9F4juSxiHnAGOD8eTUnEK9I.jpg',
          character: 'Jesuit Dean',
          created_at: null,
          updated_at: null,
        },
        {
          id: '3570914f-35e6-4d18-80d0-e58b3e412d4a',
          movie_id: 9552,
          name: 'Dick Callinan',
          original_name: 'Dick Callinan',
          popularity: '1.23',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Astronaut (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'f2dc2b55-107f-4831-8b78-d12d292f4950',
          movie_id: 9552,
          name: 'Peter Masterson',
          original_name: 'Peter Masterson',
          popularity: '1.2',
          profile_path:
            'https://image.tmdb.org/t/p/original/A5vHAGwbGJqHp5B9GBQsT6uNqKC.jpg',
          character: 'Dr. Barringer',
          created_at: null,
          updated_at: null,
        },
        {
          id: '40b3930a-edb2-4bdc-9ea7-7ba16c79d7f3',
          movie_id: 9552,
          name: 'Ann Miles',
          original_name: 'Ann Miles',
          popularity: '0.98',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Spiderwalk (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '4c3da130-fe51-4039-a21e-2e8065f1900a',
          movie_id: 9552,
          name: 'Bernard Eismann',
          original_name: 'Bernard Eismann',
          popularity: '0.98',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Minor Role (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '5b6205ec-a6ea-4ce7-94be-7e5b03db71f5',
          movie_id: 9552,
          name: 'Barton Lane',
          original_name: 'Barton Lane',
          popularity: '0.98',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Angiography Doctor (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'b7cdca36-a9a9-4f32-9322-2fab1dc5bf68',
          movie_id: 9552,
          name: 'Vincent Russell',
          original_name: 'Vincent Russell',
          popularity: '0.98',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Subway Vagrant (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'c6696fbb-9ef9-422a-a4e7-84528f7c121e',
          movie_id: 9552,
          name: 'Gina Petrushka',
          original_name: 'Gina Petrushka',
          popularity: '0.98',
          profile_path:
            'https://image.tmdb.org/t/p/original/hvxm6xNq0NywmcfgcJugKEhGP9W.jpg',
          character: 'Willi',
          created_at: null,
          updated_at: null,
        },
        {
          id: '3fb8702d-60e1-4e28-b719-b3aa7acfa8ff',
          movie_id: 9552,
          name: 'Thomas Bermingham',
          original_name: 'Thomas Bermingham',
          popularity: '0.972',
          profile_path:
            'https://image.tmdb.org/t/p/original/hGfsSJQXdbnPcAqqxOaxA7KPiaq.jpg',
          character: 'Tom',
          created_at: null,
          updated_at: null,
        },
        {
          id: '7aac96ce-7681-4082-9ddc-91ef6c20ad22',
          movie_id: 9552,
          name: 'Robert Gerringer',
          original_name: 'Robert Gerringer',
          popularity: '0.688',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Senator at Party',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'c4959306-fec2-4a01-8408-b540594181ed',
          movie_id: 9552,
          name: 'Mason Curry',
          original_name: 'Mason Curry',
          popularity: '0.612',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Doctor (voice) (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '2c623722-7005-438b-ae0b-aa8d2ec70107',
          movie_id: 9552,
          name: 'Gerard F. Yates',
          original_name: 'Gerard F. Yates',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Priest Singing Around Piano at Party (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '3def5b81-8f05-45f5-bf16-497b24036eaf',
          movie_id: 9552,
          name: 'John Nicola',
          original_name: 'John Nicola',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Priest (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '4d198609-127f-49f1-b04d-8f4df68f2b3e',
          movie_id: 9552,
          name: 'Elinore Blair',
          original_name: 'Elinore Blair',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Nurse (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '900e960c-3a71-4976-8c71-7489c2eb75e2',
          movie_id: 9552,
          name: 'Beatrice Hunter',
          original_name: 'Beatrice Hunter',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Minor Role (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: '915d193a-8f2f-429e-ab96-8111a00bb26c',
          movie_id: 9552,
          name: 'Toni Darnay',
          original_name: 'Toni Darnay',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Violent psychotic patient (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'cbfbeb98-5109-4457-865f-45edb67bced9',
          movie_id: 9552,
          name: 'Yvonne Jones',
          original_name: 'Yvonne Jones',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Bellevue Nurse (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'cc3034ea-3226-4ff1-9047-917d30feb6a2',
          movie_id: 9552,
          name: 'Don LaBonte',
          original_name: 'Don LaBonte',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: 'Minor Role (uncredited)',
          created_at: null,
          updated_at: null,
        },
        {
          id: 'e47059ac-1164-48ad-960c-fe1d13e925d6',
          movie_id: 9552,
          name: 'Paul Bateson',
          original_name: 'Paul Bateson',
          popularity: '0.6',
          profile_path: 'https://image.tmdb.org/t/p/original',
          character: "Radiologist's Assistant (uncredited)",
          created_at: null,
          updated_at: null,
        },
      ],
    },
  ];
}
